server:
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  cloud:
    nacos:
      username: nacos
      password: wz@Knet.cn
      discovery:
        server-addr: nacos.knetreg.cn:80
  datasource:
    wz:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #oracle.jdbc.driver.OracleDriver
      url: jdbc:p6spy:oracle:thin:@vdbwlk.knet.cn:1521:ora9
      username: knet
      password: kwdomain
      dbcp2:
        max-idle: 30
        min-idle: 5
        initial-size: 5
        max-wait-millis: 12000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        validation-query: select 1 from dual
        time-between-eviction-runs-millis: 180000
        num-tests-per-eviction-run: 3
        min-evictable-idle-time-millis: 180000
        remove-abandoned-on-borrow: true
        remove-abandoned-timeout: 60
      type: org.apache.commons.dbcp2.BasicDataSource
    seal:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@seal.db.knet.cn:1523:portal
      username: kx_seal
      password: cnnic
      dbcp2:
        max-idle: 30
        min-idle: 5
        initial-size: 5
        max-wait-millis: 12000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        validation-query: select 1 from dual
        time-between-eviction-runs-millis: 180000
        num-tests-per-eviction-run: 3
        min-evictable-idle-time-millis: 180000
        remove-abandoned-on-borrow: true
        remove-abandoned-timeout: 8
      type: org.apache.commons.dbcp2.BasicDataSource
#      oracleucp:
#        max-idle-time: 8
#        min-pool-size: 20
#      tomcat:
#        remove-abandoned: true
#        remove-abandoned-timeout: 8
#        time-between-eviction-runs-millis: 300000
#        min-evictable-idle-time-millis: 300000
#        test-on-return: true
#        test-on-connect: true
#        test-on-borrow: true